name: chat_gpt_boilerplate
description: "This is Chat GPT in Flutter."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  adaptive_dialog: ^2.1.0

  cached_network_image: ^3.3.1

  collection: ^1.18.0

  cupertino_icons: ^1.0.6

  dart_openai: ^5.1.0

  dropdown_button2: ^2.3.9

  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.3.2

  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1

  flutter_svg: ^2.0.10+1

  go_router: ^14.1.4

  google_fonts: ^6.2.1

  intl: ^0.19.0

  isar: ^3.1.0+1

  isar_flutter_libs: ^3.1.0+1

  loading_animation_widget: ^1.2.1

  path_provider: ^2.1.3

  photo_view: ^0.15.0

  riverpod_annotation: ^2.3.5

  share_plus: ^8.0.3

  shared_preferences: ^2.2.3

  url_launcher: ^6.2.5

  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9

  flutter_gen_runner: ^5.4.0

  flutter_test:
    sdk: flutter

  go_router_builder: ^2.7.0

  isar_generator: ^3.1.0+1

  package_rename: ^1.5.3

  riverpod_generator: ^2.4.0

  riverpod_lint: ^2.3.10

  very_good_analysis: ^5.1.0

# Isarの依存関係を解消するため
dependency_overrides:
  analyzer: ^6.0.0

flutter_gen:
  output: lib/core/gen/

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

package_rename_config:
  android:
    app_name: chatgptboilerplate
    package_name: com.example.chatgptboilerplate

  ios:
    app_name: chatgptboilerplate
    bundle_name: chatgptboilerplate
    package_name: com.example.chatgptboilerplate

  linux:
    app_name: chatgptboilerplate
    package_name: com.example.chatgptboilerplate
    exe_name: chatgptboilerplate

  macos:
    app_name: chatgptboilerplate
    package_name: com.example.chatgptboilerplate

  web:
    app_name: chatgptboilerplate
    description: This is Chat GPT in Flutter.

  windows:
    app_name: chatgptboilerplate
    organization: Never inc.
    copyright_notice: Never inc.
    exe_name: chatgptboilerplate